/* Catálogo de raças originais para seleção do personagem. */
(function () {
  const list = [
    ["elfo","Elfo","🏹","Agilidade"],["anjo","Anjo","🪽","Cura"],["demonio","Demônio","🔥","Fogo"],["dragao","Dragão","🐉","Sopro e resistência"],["humano","Humano","🛡️","Equilíbrio"],["anao","Anão","⛏️","Defesa"],["gigante","Gigante","🗿","Impacto"],["vampiro","Vampiro","🩸","Roubo de vida"],["lobisomem","Lobisomem","🐺","Regeneração"],["fada","Fada","✨","Magia"],["sereia","Sereia","🧜","Encantamento"],["tritao","Tritão","🌊","Água"],["golem","Golem","🪨","Armadura"],["elemental-fogo","Elemental de Fogo","🌋","Chamas"],["elemental-gelo","Elemental de Gelo","❄️","Congelamento"],["elemental-raio","Elemental de Raio","⚡","Velocidade"],["elemental-terra","Elemental de Terra","🌱","Resistência"],["elfo-sombrio","Elfo Sombrio","🌑","Crítico"],["elfo-lunar","Elfo Lunar","🌙","Lua"],["elfo-solar","Elfo Solar","☀️","Luz"],["orc","Orc","👹","Força"],["goblin","Goblin","👺","Engenho"],["troll","Troll","🧌","Regeneração"],["ogro","Ogro","💪","Ataque pesado"],["minotauro","Minotauro","🐂","Investida"],["centauro","Centauro","🏹","Velocidade"],["harpia","Harpia","🦅","Mobilidade"],["kitsune","Kitsune","🦊","Ilusão"],["naga","Naga","🐍","Veneno"],["draconiano","Draconiano","🦎","Escamas"],["quimera","Quimera","🦁","Instintos"],["fada-sombria","Fada Sombria","🧚","Maldição"],["espirito","Espírito","👻","Intangível"],["fantasma","Fantasma","🌫️","Furtividade"],["ceifador","Ceifador","☠️","Sombra"],["serafim","Serafim","😇","Luz superior"],["querubim","Querubim","💫","Bênção"],["demonio-azul","Demônio Azul","🔵","Gelo infernal"],["demonio-vento","Demônio do Vento","🌪️","Movimento"],["demonio-lava","Demônio de Lava","🌋","Resistência"],["cavaleiro-arcano","Cavaleiro Arcano","⚔️","Arma e magia"],["mago","Mago","🔮","Mana"],["necromante","Necromante","🕯️","Invocação"],["alquimista","Alquimista","⚗️","Poções"],["android","Autômato","🤖","Precisão"],["cristalino","Cristalino","💎","Barreira"],["guardiao-floresta","Guardião da Floresta","🌳","Cura"],["corvo-mistico","Corvo Místico","🐦‍⬛","Visão"],["leao-celestial","Leão Celestial","🦁","Coragem"],["serpente-astral","Serpente Astral","🐍","Esquiva"],["tita","Titã","🏛️","Poder colossal"]
  ];
  window.RACE_CATALOG = Object.fromEntries(list.map(([id,name,icon,trait],i)=>[id,{id,name,icon,trait,base:id.includes("anjo")||id==="serafim"||id==="querubim"?"anjo":id.includes("demonio")?"demonio":"elfo",health:100+(i%8)*12,mana:45+(i%7)*10,strength:10+(i%9)*2,defense:9+(i%8)*2,agility:10+(i%10),intelligence:10+(i%9)*2}]));
  const grid=document.querySelector(".race-options");
  if(grid) grid.innerHTML=list.map(([id,name,icon,trait],i)=>`<button class="race-card ${i===0?"selected":""}" data-race="${id}" type="button"><span class="race-icon">${icon}</span><strong>${name}</strong><small>${trait}</small></button>`).join("");
  document.getElementById("race-search")?.addEventListener("input",e=>{const q=e.target.value.toLowerCase();document.querySelectorAll(".race-card").forEach(card=>{card.hidden=!card.textContent.toLowerCase().includes(q);});});
})();
